import{a as q,S as B,i as c}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const C="https://pixabay.com/api/",$="50906092-34cf06e72a427370f235fb117";async function p(r,o=1){const n={key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await q.get(C,{params:n})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new B(".gallery a");function d(r){const o=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:a,comments:b,downloads:S})=>`
    <li class="gallery-item">
      <a href="${i}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p>Likes: ${t}</p>
        <p>Views: ${a}</p>
        <p>Comments: ${b}</p>
        <p>Downloads: ${S}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",o),M.refresh()}function O(){m.innerHTML=""}function g(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function v(){y.classList.remove("hidden")}function l(){y.classList.add("hidden")}const w=document.querySelector(".form"),P=w.elements["search-text"],x=document.querySelector(".load-more");let u="",s=1,f=0;w.addEventListener("submit",async r=>{r.preventDefault();const o=P.value.trim();if(!o){c.warning({message:"Будь ласка, введіть запит для пошуку!",position:"topCenter"});return}u=o,s=1,O(),l(),g();try{const n=await p(u,s);if(f=n.totalHits,n.hits.length===0){c.info({message:"За вашим запитом нічого не знайдено. Спробуйте інше слово.",position:"topCenter"});return}d(n.hits),d(n.hits),f>s*15?v():l()}catch{c.error({message:"Помилка при завантаженні зображень!",position:"topCenter"})}finally{L()}});x.addEventListener("click",async()=>{s+=1,g(),l();try{const r=await p(u,s);d(r.hits),E(),s*15>=f?(l(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})):v()}catch{c.error({message:"Помилка при завантаженні зображень!",position:"topCenter"})}finally{L()}});function E(){const r=document.querySelector(".gallery-item");if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
