import{a as q,S as P,i as a}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const B="https://pixabay.com/api/",C="50906092-34cf06e72a427370f235fb117";async function u(o,r=1){const n={key:C,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await q.get(B,{params:n})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),M=new P(".gallery a");function y(o){const r=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:t,views:i,comments:b,downloads:v})=>`
    <li class="gallery-item">
      <a href="${s}">
        <img src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p>Likes: ${t}</p>
        <p>Views: ${i}</p>
        <p>Comments: ${b}</p>
        <p>Downloads: ${v}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){f.innerHTML=""}function h(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function E(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const L=document.querySelector(".form"),O=L.elements["search-text"],x=document.querySelector(".load-more");let l="",c=1,w=0;L.addEventListener("submit",async o=>{o.preventDefault();const r=O.value.trim();if(!r){a.warning({message:"Please enter a search query.",position:"topCenter"});return}l=r,c=1,$(),d(),h();try{const n=await u(l,c);if(w=n.totalHits,!n.hits.length){a.info({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}y(n.hits),S()}catch{a.error({message:"Something went wrong. Please try again later.",position:"topCenter"})}finally{g()}});x.addEventListener("click",async()=>{c+=1,h(),d();try{const o=await u(l,c);y(o.hits),A(),S()}catch{a.error({message:"Error loading images!",position:"topCenter"})}finally{g()}});function S(){c*15>=w?(d(),a.info({message:"Sorry, but you have reached the end of search results.",position:"topCenter"})):E()}function A(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
